controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    controller_names: ["diff_cont", "joint_broad"]

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 50.0

    base_frame_id: base_link

    parameters:
      left_wheel_names: ['left_wheel_joint']
      right_wheel_names: ['right_wheel_joint']
      wheel_separation: 0.35
      wheel_radius: 0.05
      wheels_per_side: 1
    
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    publish_limited_velocity: true
    use_stamped_vel: false
