twist_mux:
  ros__parameters:
    lock_topics: true
    topics:
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 10
        safety_limits:
          max_linear_velocity: 0.5
          max_angular_velocity: 1.0
      tracker:
        topic   : cmd_vel_tracker
        timeout : 0.5
        priority: 20
      joystick:
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 100
